### ISSUE TITLE
[HotFix] 브라우저에 JWT가 남아있어서 생기는 문제 

### ISSUE THREAD

**Issue by Park-Jeong-Ki** [42ft-transcendence/mini_project_auth_chat#106]
## 📃 Description
SIGNUP 상태에서 창을 닫으면, 유저 DB가 삭제되는데, 그 이후에 다시 창을 열면, JWT 토큰이 남아있어서 문제가 됨
@42sangkkim 

## ☑ Todo
- [x] chatting.gateway.ts에서 jwt 토큰 불러오는것 확인
- [x] 토큰이 만료되는지 주기적으로 확인
- [x] 토큰이 만료되었을 때, 아직 열려있는 소켓을 통해 "tokenExpired"라는 정보 클라이언트에 전달
- [ ] 클라이언트에서 받아준 뒤, 로그인 페이지로 이동시켜주기
