### ISSUE TITLE
[Feature] 상세 프로필 모달 구현

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/mini_project_auth_chat#108]
## 📃 Description

채팅 창에서 프로필을 눌렀을 때, 해당 유저의 프로필이 나타났으면 좋겠습니다.

## ☑ Todo
- [x] 프로필 컴포넌트 생성
- [x] 프로필 이미지 띄우기
- [x] 프로필 닉네임 띄우기
- [x] 프로필 승률 그래프 구현
- [x] 프로필 버튼들 구현
- [x] 스타일 적용
- [x] 프로필 승률 그래프 슬라이드 적용
- [x] 동작 테스트
