### ISSUE TITLE
[Feat] 채팅 컴포넌트 개발

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#124]
## 📃 Description
채팅 페이지에 필요한 컴포넌트를 개발합니다.

## ☑ Todo
- [ ] 채팅방 리스트 아이템 (사이드바)
- [ ] 채팅방 리스트 아이템 (콘텐츠)
- [ ] 검색 바
- [ ] 채팅방 생성 모달
