### ISSUE TITLE
[Design] 회원가입 페이지 css 설정

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/mini_project_auth_chat#13]
# TODO
- [x] 입력칸 css 설정
- [x] 버튼 css 수정
- [x] 프로필 사진 설정 컴포넌트 추가
- [x] 사이드바 css 수정
- [x] 인증 페이지 로딩 화면 구현
