### ISSUE TITLE
[Feat] 채널 탐색 페이지 추가

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#130]
## 📃 Description

채널 관련 컨포넌트를 활용하여 채널 탐색, 생성, 입장, 퇴장을 할 수 있는 페이지와 라우팅을 개발합니다.

## ☑ Todo
- [ ] 채널 탐색 페이지 개발
- [ ] 채널 채팅 페이지 분리
- [ ] 라우팅 연결
- [ ] 채널 생성, 입장 흐름 구현
