### ISSUE TITLE
[Refactor] vite 절대경로 설정

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#138]
## 📃 Description
프로젝트가 커지며 import 경로가 꼬이는 현상이 발생하여 이를 해결하기 위해 vite에서 절대경로를 설정합니다.

## ☑ Todo
- [ ] vite config에서 절대경로 설정
- [ ] import 경로를 절대경로로 변경
- [ ] 이미지 경로 수정
