### ISSUE TITLE
[Feature] 채팅 페이지 구현

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/mini_project_auth_chat#15]
# TODO
- [x] #16
- [x] #18
- [x] 프로필 이미지 전역 상태로 관리
- [x] 채팅 페이지 레이아웃 설정
- [x] 채팅 기능 구현
