### ISSUE TITLE
[Feat] socket 커스텀 훅 개발

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#150]
## 📃 Description
socket 에 대한 커스텀 훅 개발

## ☑ Todo
- [x] socket 커스텀 훅 개발
- [x] socket 초기화 함수 개발
- [x] socket 재연결 함수 개발
