### ISSUE TITLE
[Fix] 프로필 이미지 경로 문제

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#159]
## 📃 Description

프로필 이미지 경로가 상대경로라서 생기는 문제를 해결합니다.

## ☑ Todo

- [ ] 초기 이미지 경로 수정
- [ ] 기본 프로필 이미지 경로 수정
- [ ] 업로드한 이미지 경로 수정
