### ISSUE TITLE
[Chore] publish 환경 생성

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#161]
## 📃 Description

개발환경 외에 배포 환경을 만듭니다.

## ☑ Todo

- [ ] 에셋 디렉토리 분리, 경로 설정
- [ ] 배포환경 nginx 도입, url정리
- [ ] 개발환경에도 동일한 경로 설정
