### ISSUE TITLE
[Fix] socket 연결 제어

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#163]
## 📃 Description

불필요한 부분에서도 소켓을 연결하는 현상을 해결합니다.

## ☑ Todo

- [ ] useChatSocket에서 연결 하지 않고 소켓만 가져오는옵션 적용
- [ ] socket connect 함수 제공
- [ ] socket disconnect 함수 제공
- [ ] socket reconnect 함수 재구성
