### ISSUE TITLE
[Feat] 전체 유저 가져오기 구현 및 닉네임 valid 검사

### ISSUE THREAD

**Issue by Park-Jeong-Ki** [42ft-transcendence/mini_project_auth_chat#77]
## 📃 Description
GET 전체 유저 가져오기 

전체유저 가져오기
GET localhost:4000/users

닉네임이 valid한지 체크하기
GET localhost:4000/users/checkNickname?nickname="new_nickname"

## ☑ Todo
- [x] 전체 유저 가져오기 (Status sort -> 순서 online , game, offline, signUp)
- [x] 닉네임이 valid한지 체크하기
- [x] refresh구현 및 호출 추가
