### ISSUE TITLE
[Feature] chat message 타입 변경

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#97]
## 📃 Description

chat message 의 타입을 변경하고 이에 따라 본인의 메세지를 callback으로 받아온다.

## ☑ Todo
- [ ] #76  , #93 병합, 이슈 해결
- [ ] Message Type, Chat Type 변경
- [ ] get_message 콜백 적용
