### ISSUE TITLE
[Refactor] 프론트 코드 작성 방식 수정

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/mini_project_auth_chat#98]
## 📃 Description

복잡한 프론트 코드의 리팩토링
- Presentation & Container 디자인 패턴 적용
- styled-components의 Theming 등 여러 기능 적용

## ☑ Todo
- [ ] 각 페이지의 Presentation & Container 적용
- [ ] styled-components theme 사용
- [ ] 컴포넌트 구조 정리
