### ISSUE TITLE
[Refactor] 회원가입 페이지 동작 변경 및 코드 리팩토링

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/mini_project_auth_chat#99]
## 📃 Description

현재 프로필 이미지가 제대로 올라오지 않는 상황 수정

https://www.notion.so/a841044775f04f01b7226ad1d922b697?pvs=4

## ☑ Todo
- [x] 프로필 이미지 업로드와 동시에 저장이 될 수 있도록 변경
- [x] 프로필 이미지를 변경해줄 때, 기존 저장된 이미지는 삭제되도록 변경
- [x] 유저 상태와 DB에도 동일하게 적용되고 있는지 확인
- [x] 닉네임을 입력할 때, 실시간으로 닉네임 검사 할 수 있도록 동작 변경
- [x] 오류 없이 모두 동작하는지 확인
